/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sensor_priority.Com.multi.nw;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.TableColumn;

/**
 *
 * @author Elcot
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        jButton2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jButton2.setText("Increase Battery Power");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Decrease Battery Power");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setText("Exit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jProgressBar1.setStringPainted(true);

        jLabel1.setText("Battery Power");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jButton6)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       
   	try
	    {
                    Connection conn = null;
	    	//Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
		//	conn=DriverManager.getConnection("jdbc:odbc:secure");
			//conn.setAutoCommit(true);
                  //      Statement st=conn.createStatement();
                    
                    
                    
                    
                                  
String url="jdbc:mysql://localhost:3306/secure";
Class.forName("com.mysql.jdbc.Driver");
conn =DriverManager.getConnection(url,"root","root");
Statement st=conn.createStatement();	
                         String clus[]={"--Select--","Cluster0","Cluster1","Cluster2"};
                                Object clussel=JOptionPane.showInputDialog(null,"Select Cluster","Cluster Selection",JOptionPane.QUESTION_MESSAGE,null,clus,null);
                               String  clustername=(String)clussel;
                                
                                if(clustername.equals("--Select--"))
                                {
                                    JOptionPane.showMessageDialog(null,"Select Cluster ");
                                }
                                else
                                {
                                     if(clustername.equals("Cluster0"))      
                                     {
                                         clustername="Cluster0";
                                     }
                                     else if(clustername.equals("Cluster1"))
                                     {
                                         clustername="Cluster1";
                                     }
                                     else if(clustername.equals("Cluster2"))
                                     {
                                         clustername="Cluster2";
                                     }
                                         
                                     value=value+5;
         jProgressBar1.setValue(value);
     
                                      String qry="select max(power) as mpower from nodelog where cluster='"+clustername+"'";  
                                      ResultSet rs=st.executeQuery(qry);
                                      int mp=0;
                                      if(rs.next())
                                      {
                                          mp=rs.getInt("mpower");
                                      }
                                      int incval=mp-(mp*value)/100;
                                      String qry1="update nodelog set power="+incval+" where power="+mp+" and cluster='"+clustername+"'";
                                      st.executeUpdate(qry1);
                                      JOptionPane.showMessageDialog(null,"Battery Power Decreased By "+value+"%");
                                      this.hide();
                                     
                                }
                        
	    }
	    catch(Exception ex)
	    {
	     ex.printStackTrace();	
	    }
         
         
     
     
    
        
        
    }//GEN-LAST:event_jButton3ActionPerformed
  int value=5;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      
     if(evt.getSource()==jButton2)
     {
         
		try
	    {
                    Connection conn = null;
	    	Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
			conn=DriverManager.getConnection("jdbc:odbc:secure");
			//conn.setAutoCommit(true);
                        Statement st=conn.createStatement();
                        
                         String clus[]={"--Select--","Cluster0","Cluster1","Cluster2"};
                                Object clussel=JOptionPane.showInputDialog(null,"Select Cluster","Cluster Selection",JOptionPane.QUESTION_MESSAGE,null,clus,null);
                               String  clustername=(String)clussel;
                                
                                if(clustername.equals("--Select--"))
                                {
                                    JOptionPane.showMessageDialog(null,"Select Cluster ");
                                }
                                else
                                {
                                     if(clustername.equals("Cluster0"))      
                                     {
                                         clustername="Cluster0";
                                     }
                                    
                                    
                                    
                                    else if(clustername.equals("Cluster1"))      
                                     {
                                         clustername="Cluster1";
                                     }
                                     else if(clustername.equals("Cluster2"))
                                     {
                                         clustername="Cluster2";
                                     }
                                     value=value+5;
         jProgressBar1.setValue(value);
     
                                      String qry="select max(power) as mpower from nodelog where cluster='"+clustername+"'";  
                                      ResultSet rs=st.executeQuery(qry);
                                      int mp=0;
                                      if(rs.next())
                                      {
                                          mp=rs.getInt("mpower");
                                      }
                                      int incval=mp+(mp*value)/100;
                                      String qry1="update nodelog set power="+incval+" where power="+mp+" and cluster='"+clustername+"'";
                                      st.executeUpdate(qry1);
                                      JOptionPane.showMessageDialog(null,"Battery Power Increased By "+value+"%");
                                      this.hide();
                                     
                                }
                        
	    }
	    catch(Exception ex)
	    {
	     ex.printStackTrace();	
	    }
         
         
     }
     
    
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
